SECRET_TOKEN : "<YOUR_IEX_SECRET_TOKEN>"
PUBLISHABLE_TOKEN : "<YOUR_IEX_PUBLISHABLE_TOKEN>"
SANDBOX_PUBLISHABLE_TOKEN: <YOUR_IEX_SANDBOX_PUBLISHABLE_TOKEN>

SENDER_EMAIL : "<YOUR_SENDER_EMAIL>"
SENDER_PWD : "<YOUR_SENDER_PWD>"
RECEIVER_EMAIL : "<YOUR_RECEIVER_EMAIL>"
trace: [AAPL]
